name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v1.0.0
      - name: Test qmake
        run: qmake ImageApp.pro && make

